version: "3"
services:
  elastic-search:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      "discovery.type": single-node
    ports:
      - "9200:9200"
      - "9300:9300"
